#!/bin/bash

# Copyright 2019-2020 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

# emfetch v1.1.1
VERSION="v1.1.1"

# Used to pre-fetch the distfiles for any updates that emupdate would like to apply. 
# My internet connection is pretty spotty. --fetchonly seems to have a much higher success rate vs downloading each source package as emupdate reaches it.

EMOPTS=""
ASK=1

ARGS=$(getopt -o 'c,b,n,v,h' --long 'changed-deps,backtrack,no-ask,version,help' -- "$@") || exit
eval "set -- $ARGS"

while true; do
    case $1 in
        (-c|--changed-deps)
                EMOPTS="${EMOPTS} --changed-deps"; shift;;
        (-b|--backtrack)
                EMOPTS="${EMOPTS} --backtrack=100"; shift;;
        (-n|--no-ask)
                ASK=0; shift;;
        (-v|--version)
                echo "emfetch ${VERSION}"; exit;;
        (-h|--help)
                echo "emfetch ${VERSION}"
                echo ""
                echo "-c,--changed-deps:	Add --changed-deps to emerge call."
                echo "-b,--backtrack:		Add --backtrack=100 to emerge call."
                echo "-n,--no-ask:      	Do not add --ask to emerge call."
                echo "-v,--version:     	Print version and exit."
                echo "-h,--help:        	Print this message and exit."
                exit;;
		(--)    shift; break;;
        (*)     break;;
    esac
done

if [ "$ASK" == 1 ]; then
    EMOPTS="${EMOPTS} --ask"
fi

/usr/bin/emerge --fetchonly $EMOPTS --update --deep --newuse --changed-use --keep-going @world

