#!/bin/bash

# Copyright 2019-2025 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

# emmakekernel v1.2.3
# Used to build a new kernel and all associated steps in installing it,
# as well as rebuilding any installed modules.

source /etc/emtools.conf

if ! grep -qs '/boot ' /proc/mounts; then
	echo "/boot must be mounted!"
	exit
fi

if [ "$emtools_firmware" != "" ]; then
	emerge --update ${emtools_firmware}
fi

# Move to kernel source
cd /usr/src/linux

# Make kernel and modules

/usr/bin/make ${emtools_kernproc} prepare
/usr/bin/make ${emtools_kernproc} modules_prepare
/usr/bin/make ${emtools_kernproc}
/usr/bin/make ${emtools_kernproc} modules_install

# Install kernel to /boot
/usr/bin/make ${emtools_kernproc} install

#TODO: Delete older kernels from /boot

# Backup /boot to $emtools_bootbak if it is set
if [ ! -z "$emtools_bootbak" ]; then
	/usr/bin/rsync -av /boot/ ${emtools_bootbak}

fi

# Rebuild other modules
emerge --keep-going @module-rebuild

