#!/bin/bash

# Copyright 2019 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

# emsync v1.0.0
# Used to sync the main gentoo tree and anything else that's available.

/usr/sbin/emaint sync --auto
/usr/bin/layman -s ALL
/usr/bin/eix-update

