#!/bin/bash

# Copyright 2019-2025 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

VERSION="v1.1.3"

# Used to sync the main gentoo tree and anything else that's available.
# The utility of this script was much greater before eselect-repository was a thing.
# It's a bit superfluous now.

SYNC=0
EIX=0

ARGS=$(getopt -o 'a,e,v,h' --long 'all,eix,version,help' -- "$@") || exit
eval "set -- $ARGS"

while true; do
    case $1 in
		(-a|--all)
				SYNC=1; EIX=1; shift;;        
		(-e|--eix)
                EIX=1; shift;;
		(-v|--version)
				echo "emsync ${VERSION}"; exit;;
		(-h|--help)
				echo "emsync ${VERSION}"
				echo ""
				echo "-a,--all:	Sync all repos, and update eix db."
				echo "-e,--eix:	Update eix database."
				echo "-v,--version:	Print version and exit."
				echo "-h,--help:	Print this message and exit."
				exit;;
        (--)    shift; break;;
        (*)     break;;
    esac
done

if [ "$SYNC" == 0 ] && [ "$EIX" == 0 ]; then
	SYNC=1
	EIX=1
fi

if [ "$SYNC" == 1 ]; then
	/usr/sbin/emaint -A sync
fi

if [ "$EIX" == 1 ]; then
	mv /var/cache/eix/portage.eix /var/cache/eix/previous.eix
	/usr/bin/eix-update
fi

