#!/bin/bash

# Copyright 2019-2021 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

# emupdate v1.1.4
VERSION="v1.1.4"

# To be used after emsync. Updates the system and cleans up the mess.

# This was used to allow installed packages that are no longer in tree to stay installed without causing annoying warnings.
# Leaving here for reference in case I need it again.
#source /etc/portage/package.excludes
#/usr/bin/emerge --exclude "$NOTOUCH" --backtrack=100 --ask --changed-deps --update --deep --newuse --keep-going @world

EMOPTS=""
ASK=1

ARGS=$(getopt -o 'c,b,n,v,h' --long 'changed-deps,backtrack,no-ask,version,help' -- "$@") || exit
eval "set -- $ARGS"

while true; do
	case $1 in
		(-c|--changed-deps)
				EMOPTS="${EMOPTS} --changed-deps"; shift;;
		(-b|--backtrack)
				EMOPTS="${EMOPTS} --backtrack=100"; shift;;
		(-n|--no-ask)
				ASK=0; shift;;
		(-v|--version)
				echo "emupdate ${VERSION}"; exit;;
		(-h|--help)
				echo "emupdate ${VERSION}"
				echo ""
				echo "-c,--changed-deps:	Add --changed-deps to emerge call."
				echo "-b,--backtrack:		Add --backtrack=100 to emerge call."
				echo "-n,--no-ask:		Do not add --ask to emerge call."
				echo "-v,--version:		Print version and exit."
				echo "-h,--help:		Print this message and exit."
				exit;;
		(--) 	shift; break;;
		(*)		break;;
	esac
done

if [ "$ASK" == 1 ]; then
	EMOPTS="${EMOPTS} --ask"
fi

if [ -e "/etc/init.d/boinc" ]; then
	echo "Stopping boinc"
	/sbin/rc-service boinc stop > /dev/null  2>&1 &
fi

/usr/bin/emerge $EMOPTS --update --deep --changed-use --keep-going @world

if [ "$?" == 0 ]; then
	/usr/bin/emerge @preserved-rebuild
	/usr/bin/emerge --ask --depclean
	/usr/bin/eclean-dist --deep
else
	/usr/bin/eclean-dist
fi

if [ -e "/etc/init.d/boinc" ]; then
    echo "Re-starting boinc"
    /sbin/rc-service boinc start > /dev/null  2>&1 &
fi

