#!/bin/bash

# Copyright 2019-2021 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

# emwhen v1.0.1
# Displays the date and time of the last sync of the main gentoo repo.

EMWHERE="/usr/portage/metadata/timestamp"
if [[ ! -f "$EMWHERE" ]]; then
	EMWHERE="/var/db/repos/gentoo/metadata/timestamp"
fi

date -r "$EMWHERE"
