#!/bin/bash

# Copyright 2019-2025 Dallen Wilson
# Distributed under the terms of the GNU General Public License v3

# emwhen v1.0.2
# Displays the date and time of the last sync of the main gentoo repo.

EMWHERE="/var/db/repos/gentoo/metadata/timestamp.chk"
if [[ ! -f "$EMWHERE" ]]; then
	EMWHERE="/var/db/repos/gentoo/metadata/timestamp"
fi

if [[ ! -f "$EMWHERE" ]]; then
	echo "Unable to locate gentoo repo timestamp."
	exit 1
fi

date -r "$EMWHERE"
